# Dependencies
highligher:         true

# Permalinks
permalink:        pretty

# Setup
title:            Last Week Tonight Companion
tagline:          LWTB - Dig Deeper
url:              http://ethankale.github.io/last-week-tonight-background/
paginate:         5
baseurl:          http://ethankale.github.io/last-week-tonight-background/
author:
  name:           Nat Kale
  url:            https://github.com/ethankale
  email:          nathaniel.kale+lwtb@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/ethankale/last-week-tonight-background
